name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.USER_TOKEN }}
          filename: metrics.svg

          base: header
          config_timezone: America/Sao_Paulo

          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_sections: most-used
          plugin_languages_limit: 5

          plugin_repositories: yes
